import { useState } from "react";
import { Search, RefreshCw, CheckCircle, XCircle, Eye, Play, Zap, ChevronDown, ChevronUp } from "lucide-react";
import Badge from "../components/Badge";
import { mockRecommendations, type Recommendation } from "../data/mockData";

type Status = Recommendation["status"];

function priorityColor(p: string) {
  if (p === "Critical") return "red";
  if (p === "High") return "amber";
  if (p === "Medium") return "blue";
  return "gray";
}
function effortColor(e: string) {
  if (e === "Low") return "green";
  if (e === "Medium") return "amber";
  return "red";
}

export default function Recommendations() {
  const [recs, setRecs] = useState<Recommendation[]>(mockRecommendations);
  const [search, setSearch] = useState("");
  const [filterPriority, setFilterPriority] = useState("All");
  const [filterCategory, setFilterCategory] = useState("All");
  const [filterStatus, setFilterStatus] = useState("All");
  const [expanded, setExpanded] = useState<string | null>(null);
  const [refreshing, setRefreshing] = useState(false);
  const [toast, setToast] = useState<string | null>(null);

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }

  function updateStatus(id: string, status: Status) {
    setRecs((r) => r.map((x) => x.id === id ? { ...x, status } : x));
    showToast(status === "Accepted" ? "Recommendation accepted." : status === "Dismissed" ? "Recommendation dismissed." : "Status updated.");
  }

  function handleRefresh() {
    setRefreshing(true);
    setTimeout(() => { setRefreshing(false); showToast("AI analysis refreshed (Demo Mode)."); }, 1200);
  }

  const categories = ["All", ...Array.from(new Set(recs.map((r) => r.category)))];

  const filtered = recs.filter((r) => {
    if (filterPriority !== "All" && r.priority !== filterPriority) return false;
    if (filterCategory !== "All" && r.category !== filterCategory) return false;
    if (filterStatus !== "All" && r.status !== filterStatus) return false;
    if (search) {
      const q = search.toLowerCase();
      return r.title.toLowerCase().includes(q) || r.resourceName.toLowerCase().includes(q) || r.category.toLowerCase().includes(q);
    }
    return true;
  });

  const totalSavings = filtered.filter((r) => r.status !== "Dismissed").reduce((s, r) => s + r.monthlySavings, 0);
  const pendingCount = filtered.filter((r) => r.status === "Pending").length;

  return (
    <div className="p-6 space-y-5 max-w-[1400px] relative">
      {/* Toast */}
      {toast && (
        <div className="fixed top-4 right-4 z-50 bg-green-500/20 border border-green-500/40 text-green-400 text-sm rounded-xl px-4 py-3 shadow-lg">
          {toast}
        </div>
      )}

      {/* Summary */}
      <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
        {[
          { label: "Total Potential Savings", value: `$${totalSavings.toFixed(0)}/mo`, sub: `$${(totalSavings * 12).toFixed(0)}/yr`, color: "text-green-400" },
          { label: "Pending Review", value: `${pendingCount}`, color: "text-amber-400" },
          { label: "Accepted", value: `${recs.filter((r) => r.status === "Accepted").length}`, color: "text-cyan-400" },
          { label: "AI Engine", value: "Demo Mode", color: "text-slate-400" },
        ].map((s) => (
          <div key={s.label} className="bg-[#0a1628] border border-[#1e3a6e]/60 rounded-xl p-4">
            <p className="text-xs text-slate-500 mb-1">{s.label}</p>
            <p className={`text-xl font-mono font-semibold ${s.color}`}>{s.value}</p>
            {s.sub && <p className="text-xs text-slate-500 mt-0.5">{s.sub}</p>}
          </div>
        ))}
      </div>

      {/* Demo AI banner */}
      <div className="flex items-center justify-between bg-[#0a1628] border border-[#1e3a6e]/60 rounded-xl px-4 py-3">
        <div className="flex items-center gap-2 text-sm text-slate-400">
          <Zap size={14} className="text-amber-400" />
          <span>Recommendations generated by a <strong className="text-amber-400">rule-based demo engine</strong>. Connect a real LLM API in <code className="text-cyan-400 text-xs">src/services/aiService.ts</code> for production use.</span>
        </div>
        <button onClick={handleRefresh} className="flex items-center gap-1 bg-[#0f2040] border border-[#1e3a6e] text-slate-300 text-xs rounded-lg px-3 py-1.5 hover:border-cyan-500/40 transition-colors ml-3 flex-shrink-0">
          <RefreshCw size={11} className={refreshing ? "animate-spin" : ""} />
          Refresh AI Analysis
        </button>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3 items-center bg-[#0a1628] border border-[#1e3a6e]/60 rounded-xl p-4">
        <div className="flex items-center gap-2 bg-[#0f2040] border border-[#1e3a6e] rounded-lg px-3 py-2 flex-1 min-w-48">
          <Search size={13} className="text-slate-400" />
          <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search recommendations…" className="bg-transparent text-sm text-white placeholder-slate-600 outline-none flex-1" />
        </div>
        {[
          { value: filterPriority, set: setFilterPriority, opts: ["All", "Critical", "High", "Medium", "Low"], label: "Priority" },
          { value: filterCategory, set: setFilterCategory, opts: categories, label: "Category" },
          { value: filterStatus, set: setFilterStatus, opts: ["All", "Pending", "Accepted", "Dismissed", "Applied"], label: "Status" },
        ].map((f) => (
          <select key={f.label} value={f.value} onChange={(e) => f.set(e.target.value)} className="bg-[#0f2040] border border-[#1e3a6e] text-slate-300 text-xs rounded-lg px-2 py-2 focus:outline-none">
            {f.opts.map((o) => <option key={o}>{o}</option>)}
          </select>
        ))}
        <span className="text-xs text-slate-500 font-mono ml-auto">{filtered.length} found</span>
      </div>

      {/* List */}
      <div className="space-y-3">
        {filtered.length === 0 && (
          <div className="text-center py-12 text-slate-500">No recommendations match your filters.</div>
        )}
        {filtered.map((r) => (
          <div key={r.id} className={`bg-[#0a1628] border rounded-xl overflow-hidden transition-colors ${r.status === "Dismissed" ? "opacity-50 border-[#1e3a6e]/30" : "border-[#1e3a6e]/60 hover:border-[#254a88]/80"}`}>
            <div className="p-4 flex items-start gap-4">
              <div className={`w-2 h-2 rounded-full flex-shrink-0 mt-2 ${r.priority === "Critical" ? "bg-red-400" : r.priority === "High" ? "bg-amber-400" : r.priority === "Medium" ? "bg-blue-400" : "bg-slate-500"}`} />
              <div className="flex-1 min-w-0">
                <div className="flex flex-wrap items-center gap-2 mb-1">
                  <h3 className="text-sm font-semibold text-white">{r.title}</h3>
                  <Badge label={r.priority} variant={priorityColor(r.priority) as "red" | "amber" | "blue" | "gray"} />
                  <Badge label={r.category} variant="cyan" />
                  <Badge label={r.status} variant={r.status === "Accepted" ? "green" : r.status === "Dismissed" ? "gray" : "amber"} />
                </div>
                <p className="text-xs text-slate-400 mb-2">{r.description}</p>
                <div className="flex flex-wrap gap-4 text-xs">
                  <span className="text-slate-500">Resource: <span className="text-white font-mono">{r.resourceName}</span></span>
                  <span className="text-slate-500">Provider: <span className="text-white">{r.provider}</span></span>
                  <span className="text-slate-500">Region: <span className="font-mono text-white">{r.region}</span></span>
                  <span className="text-slate-500">Effort: <Badge label={r.effort} variant={effortColor(r.effort) as "green" | "amber" | "red"} /></span>
                  <span className="text-slate-500">Risk: <Badge label={r.riskLevel} variant={r.riskLevel === "Low" ? "green" : r.riskLevel === "Medium" ? "amber" : "red"} /></span>
                </div>
              </div>
              <div className="flex-shrink-0 text-right">
                <div className="text-green-400 font-mono font-semibold text-sm">+${r.monthlySavings.toFixed(0)}/mo</div>
                <div className="text-slate-500 font-mono text-xs">${r.annualSavings.toFixed(0)}/yr</div>
              </div>
            </div>

            {/* Expanded details */}
            {expanded === r.id && (
              <div className="border-t border-[#1e3a6e]/60 px-4 pb-4 pt-4 grid sm:grid-cols-2 gap-4 bg-[#0f2040]/40">
                <div>
                  <p className="text-[10px] text-slate-500 uppercase tracking-wide mb-1">Why this recommendation</p>
                  <p className="text-xs text-slate-300">{r.reason}</p>
                </div>
                <div>
                  <p className="text-[10px] text-slate-500 uppercase tracking-wide mb-1">Suggested action</p>
                  <p className="text-xs text-slate-300">{r.suggestedAction}</p>
                </div>
              </div>
            )}

            {/* Actions */}
            <div className="border-t border-[#1e3a6e]/40 px-4 py-2.5 flex items-center gap-2 bg-[#0f2040]/20">
              <button onClick={() => setExpanded(expanded === r.id ? null : r.id)} className="flex items-center gap-1 text-xs text-slate-400 hover:text-cyan-400 transition-colors">
                <Eye size={12} />
                {expanded === r.id ? "Less" : "Details"}
                {expanded === r.id ? <ChevronUp size={11} /> : <ChevronDown size={11} />}
              </button>
              {r.status === "Pending" && (
                <>
                  <button onClick={() => updateStatus(r.id, "Accepted")} className="flex items-center gap-1 text-xs text-green-400 hover:text-green-300 transition-colors ml-2">
                    <CheckCircle size={12} />Accept
                  </button>
                  <button onClick={() => updateStatus(r.id, "Dismissed")} className="flex items-center gap-1 text-xs text-slate-500 hover:text-red-400 transition-colors">
                    <XCircle size={12} />Dismiss
                  </button>
                  <button className="flex items-center gap-1 text-xs text-purple-400 hover:text-purple-300 transition-colors">
                    <Play size={12} />Simulate
                  </button>
                </>
              )}
              {r.status === "Dismissed" && (
                <button onClick={() => updateStatus(r.id, "Pending")} className="text-xs text-slate-500 hover:text-slate-300 transition-colors ml-2">Restore</button>
              )}
              <span className="ml-auto text-[10px] text-slate-600 font-mono">{r.createdAt}</span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
